spring:
  config:
    import:
      - oauth.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mentoring-mysql.cho8m9hxcz0n.ap-northeast-2.rds.amazonaws.com/test
    username: admin
    password: fbwls9663
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
