spring:
  profiles:
    include:
      - oauth.yml
  config:
    import:
      - oauth.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: zerobase
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
